// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDDT2aFMNvYe1YVlYEVK3yucqQNfv8k5g',
    appId: '1:94152569178:web:cfa3bb5ee6660fc4cc4363',
    messagingSenderId: '94152569178',
    projectId: 'mastivibes-ec7b1',
    authDomain: 'mastivibes-ec7b1.firebaseapp.com',
    storageBucket: 'mastivibes-ec7b1.firebasestorage.app',
    measurementId: 'G-TDNC6KQ1B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE3V7ZPtQBWF8xw1j57PLLJmuf6901Wi4',
    appId: '1:94152569178:android:8d49145b2cac2737cc4363',
    messagingSenderId: '94152569178',
    projectId: 'mastivibes-ec7b1',
    storageBucket: 'mastivibes-ec7b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE5qZoZaHzyiBtuXG3Ejxqhk8RDsAOqbk',
    appId: '1:94152569178:ios:22d548861aa3bdafcc4363',
    messagingSenderId: '94152569178',
    projectId: 'mastivibes-ec7b1',
    storageBucket: 'mastivibes-ec7b1.firebasestorage.app',
    iosBundleId: 'com.example.alludeUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE5qZoZaHzyiBtuXG3Ejxqhk8RDsAOqbk',
    appId: '1:94152569178:ios:22d548861aa3bdafcc4363',
    messagingSenderId: '94152569178',
    projectId: 'mastivibes-ec7b1',
    storageBucket: 'mastivibes-ec7b1.firebasestorage.app',
    iosBundleId: 'com.example.alludeUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDDT2aFMNvYe1YVlYEVK3yucqQNfv8k5g',
    appId: '1:94152569178:web:be4806533ea87084cc4363',
    messagingSenderId: '94152569178',
    projectId: 'mastivibes-ec7b1',
    authDomain: 'mastivibes-ec7b1.firebaseapp.com',
    storageBucket: 'mastivibes-ec7b1.firebasestorage.app',
    measurementId: 'G-WN90ZEDVTH',
  );
}
